export const API_PREFIX_SERVER = process.env.NEXT_PUBLIC_API_PREFIX_SERVER;
export const API_PREFIX_LOCAL = process.env.NEXT_PUBLIC_API_PREFIX_LOCAL;
export const AUTH_SECRET = process.env.NEXT_PUBLIC_AUTH_SECRET;
export const VIBRANIUM_APP_KEY = process.env.NEXT_PUBLIC_VIBRANIUM_APP_KEY;
export const API_PREFIX_UBUNTU_SERVER =
  process.env.NEXT_PUBLIC_API_PREFIX_OLD_SERVER;
export const API_PREFIX_UBUNTU_SERVER_NEW =
  process.env.NEXT_PUBLIC_API_PREFIX_NEW_SERVER;
export const BASE_CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_BASE_CONTRACT_ADDRESS;